[phases.setup]
nixPkgs = ["python310", "postgresql", "gcc", "libpq", "postgresql.lib", "python310Packages.psycopg2"]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  ". /opt/venv/bin/activate && pip install --upgrade pip",
  ". /opt/venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
cmds = [". /opt/venv/bin/activate && python manage.py collectstatic --noinput"]

[start]
cmd = ". /opt/venv/bin/activate && gunicorn agro_diagnosis.wsgi:application"